server:
    port: 8001
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        ip-address: true
        instance-id: springcloud-provider-8001
spring:
    application:
        name: microservice-provider-user
    datasource:
        hikari:
            connection-test-query: SELECT 1
            connection-timeout: 30000
            driverClassName: org.postgresql.Driver
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 200
            minimum-idle: 10
            pool-name: masterHikariCP
            type: com.zaxxer.hikari.HikariDataSource
        mysql:
            hikari:
                connection-test-query: SELECT 1
                connection-timeout: 30000
                driverClassName: com.mysql.jdbc.Driver
                idle-timeout: 600000
                max-lifetime: 1800000
                maximum-pool-size: 20
                minimum-idle: 10
                pool-name: mysqlHikariCP
                type: com.zaxxer.hikari.HikariDataSource
    redis:
        pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
            testOnBorrow: true
            testWhileIdle: true
        timeout: 0
    session:
        store-type: redis
