server:
    port: 9527
spring:
   application:
    name: springcloud-zuul
eureka:
  client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
     instance-id: zuul9527.com
     prefer-ip-address: true
info:
   app.name: kuang-springcloud
   company.name: blog.qiangstudy.com

zuul:
   routes:
     myprovider.serviceId: microservice-provider-user
     myprovider.path: /myprovider/**
   ignored-services: "*"   # 不能再使用这个路径进行访问了，ignored 忽略  "*"代表隐藏全部
   prefix: /qiang  # 设置公共的前缀